### PR TITLE
Refactored Code

### PR DESCRIPTION
**Pull request by mrbesen**
Removed some duplicated code and used ```print``` instead of ```os.system()``` (because its faster and cleaner).
I also made the file executeable and added the python header so you can do ```./main.py``` to start it

### CODE REVIEW

**Comment by malav097** [comment]
The problem with this merge is that @avanishsubbiah was working today in a lot of new features and i think this is going to create conflicts, i know there is refactorization that has to be done (for example create a main class and use frames as attributes) but for functionality purposes i think we can base the refactor on @avanishsubbiah code. What do you think @mrbesen ?

**Comment by avanisubbiah** [comment]
I've recently refactored a lot of the multi-threading code to avoid shared reasource conflicts, but there definitely needs to be an overhaul of how animations are stored. I think we could create animation objects that store frame arrays, a function that when passed utilization parameters returns true or false if the animation state is active, and a unique state id. (I'm not sure if this the optimal way of handling the modularization of animations so any ideas are appreciated)

Also I agree with @mrbesen suggestion to use print instead of os.system() if possible because the "printf" creates incompatibility with Powershell. I don't see the need to create such an incompatibility when every other aspect of the program besides the display portion works fine under Windows 10 (psutil has an included Windows 10 binary).

This would standardize the creation of new animations in a way that doesn't require editing global variables, or the thread functions in significant ways when adding new animations to the program, and potentially make the program compatible with Powershell.

**Comment by avanisubbiah** [comment]
I've added @mrbesen 's changes to my fork of the project with a pending pull request. The program confirmed works with Windows 10 and Powershell as well now thanks to the removal of `printf` and `os.system()`.

**Comment by mrbesen** [comment]
I think its more important, to pull #10

**Pull request closed without merging**
