### PR TITLE
Added Animation class

### PR DESCRIPTION
**Pull request by avanisubbiah**
I've refactored the code for animations in my fork of the project. The program now uses the class "animation.py" in the folder "lib" which has the properties `name` `id` `file_path` and `frames`.

The constructor of the `Animation` class imports all ascii frames from `./assets/frames/<name>`. In `./assets/frames/<name>` the ascii text frames are numbered from 0-N (The animation can be of variable length and the constructor will handle it just fine).

In the main method, all animation objects are attached as values to an `emotion` dictionary that uses `<name>` as the key.

To add new emotions you just have to create a folder in assets named `<name>` and add that `<name>` to the global `emotion_names` list. Then just add all the frames (named 0-N) into the folder you just created.

### CODE REVIEW

**Comment by malav097** [comment]
Please check the new commit on this branch. Right now this merge creates a conflict. I am open to suggestions on my latest commit so feel free to judge it and express your opinion.

**Comment by avanisubbiah** [comment]
@malav097 I think the organization of lib and cfg works well (The cfg.py file you added will be great for managing the frame-time delay, file paths, etc.); however, while the commit moves the code in separate files it does not fix the issue of ease of animation addition and management because all the animations are still manually loaded in emotions.py file.

Currently, in my version a user just needs to add a folder with the name of the emotion animation into "assets/frames" with the 0-N frames, and the program will automatically detect it, assign it a state id, and add it and the frames to a master dictionary of each emotion's name and emotion object upon startup. (The emotion object contains the `name`, `id`, and `frames` of the emotion).

For example, with this workflow it would take 2 steps to implement the emotion "happy":

 - Create folder "happy" in ./assets/frames with 0-N ascii frames
 - Add 2 lines of code in `state_update` for the conditional to set `state = emotions["happy"].id`

I believe we should retain your formatting for organizing the files and use my current Animation class system.

**Comment by malav097** [comment]
@avanishsubbiah ok perfect and what do you think about converting your functions in threathing.py into one object? yesterday i sended you an invite to become collaborator. Right now i am at work and don't have time to solve merging conflicts but i think you as collaborator should be able to solve the conflicts and merge this by yourself if you don't want to wait for me.

**Comment by avanisubbiah** [comment]
> @avanishsubbiah ok perfect and what do you think about converting your functions in threathing.py into one object? yesterday i sended you an invite to become collaborator. Right now i am at work and don't have time to solve merging conflicts but i think you as collaborator should be able to solve the conflicts and merge this by yourself if you don't want to wait for me.

The functions in threading.py could be merged into one object but I'm not sure how to go about it that would be useful. At least from my understanding there should only ever be two threads (one to query utilization and update state and another to print to display), so it doesn't benefit from the ability of objects to be instantiated repeatedly.

I could try creating a thread class or helper function that creates, starts, sets Daemon, and joins a new thread, while taking the name of the function the thread requires as input? (In case you want to add more threads in the future, which could be useful for querying cpu, disk, gpu, etc. usage in parallel in the future)

For now I'll just solve the merge conflicts, lemme know when you're free on how you think the threading code could be organized

**Pull request merged**
